# Generated by Django 6.1.1 on 2026-10-08 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS_DENIED', 'Acceso denegado'), ('ACCESS_GRANTED', 'Acceso concedido'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_ACTIVATED', 'Usuario activado'), ('USER_DEACTIVATED', 'Usuario desactivado'), ('TOKEN_ISSUED', 'Token emitido'), ('TOKEN_REVOKED', 'Token revocado'), ('AUTHORIZATION_DENIED', 'Autorización denegada'), ('ROLE_ASSIGNED', 'Rol asignado'), ('ROLE_REMOVED', 'Rol retirado')], max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=1000)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_39eebe_idx'), models.Index(fields=['application', 'created_at'], name='audit_audit_applica_901048_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_audit_event_t_124af2_idx'), models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx')],
            },
        ),
    ]
