# Generated by Django 6.1.1 on 2026-10-08 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('authorization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessapplications',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='authorization.role'),
        ),
        migrations.AddField(
            model_name='accessapplications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessapplications',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalaccessapplications',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalaccessapplications',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccessapplications',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authorization.role'),
        ),
        migrations.AddField(
            model_name='historicalaccessapplications',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accessapplications',
            index=models.Index(fields=['user', 'application'], name='access_appl_user_id_1139e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessapplications',
            constraint=models.UniqueConstraint(fields=('user', 'application'), name='unique_user_application'),
        ),
    ]
