# Generated by Django 6.1.1 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_historicaloidcclient_oidcclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('soon', 'Próximamente'), ('available', 'Disponible')], default='new', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('soon', 'Próximamente'), ('available', 'Disponible')], default='new', max_length=20, verbose_name='Estado'),
        ),
    ]
